walls: 
  - name: "table"
    x_thickness: 1.5
    y_thickness: 1.25
    z_thickness: 0.05
    qx: 0
    qy: 0
    qz: 0
    qw: 1
    x: 0.0
    y: 0.0
    z: 0.0
    frame_id: world
  - name: "back_wall"
    x_thickness: 2.00
    y_thickness: 0.75 
    z_thickness: 0.05
    qx: 0.70711 
    qy: 0
    qz: 0
    qw: 0.70711
    x: 0.3
    y: 1.0
    z: 0.3
    frame_id: world
  - name: "right_wall"
    x_thickness: 1.75
    y_thickness: 1.75
    z_thickness: 0.05
    qx: 0
    qy: 0.70711 
    qz: 0
    qw: 0.70711
    x: -0.75
    y: 0.75
    z: -0.0255
    frame_id: world
  - name: "left_wall"
    x_thickness: 1.75
    y_thickness: 1.75
    z_thickness: 0.05
    qx: 0
    qy: 0.70711
    qz: 0
    qw: 0.70711
    x: 0.5
    y: 0.75
    z: -0.0255
    frame_id: world

