walls: 
  - name: "table"
    x_thickness: 1.75
    y_thickness: 1.75
    z_thickness: 0.05
    qx: 0
    qy: 0
    qz: 0
    qw: 1
    x: -0.4
    y: 0.0
    z: 0.01
    frame_id: robot_base
  - name: "right_wall"
    x_thickness: 2.00
    y_thickness: 0.75 
    z_thickness: 0.05
    qx: 0.70711 
    qy: 0
    qz: 0
    qw: 0.70711
    x: -0.6
    y: 0.75
    z: 0.4
    frame_id: robot_base
  - name: "left_wall"
    x_thickness: 2.00
    y_thickness: 0.75
    z_thickness: 0.05
    qx: 0.70711 
    qy: 0
    qz: 0
    qw: 0.70711
    x: -0.6
    y: -0.75
    z: 0.4
    frame_id: robot_base
  - name: "back_wall"
    x_thickness: 0.75
    y_thickness: 2.00
    z_thickness: 0.05
    qx: 0
    qy: 0.70711
    qz: 0
    qw: 0.70711
    x: 0.5
    y: 0.0
    z: 0.4
    frame_id: robot_base

